- label: 'chore'
  branch:
    - '/chore\/.+/'
- label: 'bug'
  branch:
    - '/fix\/.+/'
- label: 'bug'
  branch:
    - '/bugfix\/.+/'
- label: 'feature'
  branch:
    - '/feat\/.+/'
- label: 'documentation'
  branch:
    - '/docs\/.+/'
- label: 'build'
  branch:
    - '/ci\/.+/'
- label: 'refactoring'
  branch:
    - '/ref\/.+/'
- label: 'refactoring'
  branch:
    - '/perf\/.+/'
- label: 'refactoring'
  branch:
    - '/refactor\/.+/'
