name: CI

on:
  workflow_call:
    inputs:
      runner:
        description: 'Choose a runner, only for PhpUnit tests'
        required: false
        default: self-hosted
        type: string
jobs:
  pint:
    name: Laravel Pint Linting
    runs-on: ${{ inputs.runner }}
    container: industrialists/php83-pcov:1.0.1
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🧙 Configure Composer & Install Dependencies
        run: composer config --auth github-oauth.github.com "${{ secrets.COMPOSER_ACCESS_TOKEN }}" && composer i

      - name: 🔧  Run linter
        run: vendor/bin/pint -vv --config ruleset-pint.json --test

#  phpmd:
#    name: Php Mess Detector - Check
#    runs-on: ubuntu-latest
#    steps:
#      - name: 🛫 Checkout
#        uses: actions/checkout@v4
#
#      - name: 🔨 Setup php
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 8.1
#          tools: phpmd
#
#      - name: 🔧  Run Check
#        run: phpmd src text cleancode,codesize,controversial,design,unusedcode


  test:
    name: 🔨 PHPUnit
    runs-on: ${{ inputs.runner }}
    container: industrialists/php83-pcov:1.0.1
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🧙 Configure Composer & Install Dependencies
        run: composer config --auth github-oauth.github.com "${{ secrets.COMPOSER_ACCESS_TOKEN }}" && composer i

      - name: Inject Environment Variables
        uses: stetind/stem-reusable-workflows/.github/composite/inject-variables@gs/testing
        with:
          secrets-context: ${{ toJson(secrets) }}
          vars-context: ${{ toJson(vars) }}

      - name: 🔧 Execute Unit Tests
        run: vendor/bin/testbench package:test --env=true --parallel --coverage --min=90 --configuration=phpunit.xml
        env:
          APP_URL: http://127.0.0.1:8001



#  document:
#    name: Update Documentation
#    runs-on: ubuntu-latest
#    steps:
#      - name: 📖 Generate documentation
#        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} #I will only run on the main branch and not on pull request
#        uses: convictional/trigger-workflow-and-wait@v1.6.1
#        with:
#          owner: stetind
#          repo: stem-documentation
#          github_token: ${{ secrets.COMPOSER_ACCESS_TOKEN }}
#          workflow_file_name: docs.yaml
#          wait_workflow: false
