name: CI

on:
  workflow_call:
    secrets:
      COMPOSER_ACCESS_TOKEN:
        required: true

env:
  PHP_VERSION: 8.1

jobs:
  pint:
    name: Laravel Pint Linting
    runs-on: ubuntu-latest
    needs: [ "arch-test" ]
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: Cache the dependencies
        uses: actions/cache@v3
        id: cache-db
        with:
          path: vendor/
          key: db

      - name: 🔨 Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: 🧙 Configure Composer
        run: composer config --auth github-oauth.github.com "${{ secrets.COMPOSER_ACCESS_TOKEN }}"

      - name: 🔧  Run linter
        run: vendor/bin/pint -vv --config ruleset-pint.json --test


  arch-test:
    name: Architecture Test
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: Cache the dependencies
        uses: actions/cache@v3
        id: cache-db
        with:
          path: vendor/
          key: db

      - name: 🔨 Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: 🧙 Configure Composer
        run: composer config --auth github-oauth.github.com "${{ secrets.COMPOSER_ACCESS_TOKEN }}"

      - name: 🧙 Install Dependencies
        uses: ramsey/composer-install@v2

      - name: 🚓 Run test
        run: vendor/bin/deptrac -v --report-uncovered --fail-on-uncovered

#  security-check:
#    name: Vulnerability Check
#    runs-on: ubuntu-latest # be careful, we are using google-chrome, that pre-exists on ubuntu:20. Ubuntu 22 doesn't have it as default
#    steps:
#      - name: 🛫 Checkout
#        uses: actions/checkout@v3
#
#      - name: Cache the vulnerability database
#        uses: actions/cache@v3
#        id: cache-db
#        with:
#          path: ~/.symfony/cache
#          key: db
#
#      - name: 💩 Run security check
#        uses: symfonycorp/security-checker-action@v5
#        with:
#          disable-exit-code: 1

#  document:
#    name: Update Documentation
#    runs-on: ubuntu-latest
#    steps:
#      - name: 📖 Generate documentation
#        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} #I will only run on the main branch and not on pull request
#        uses: convictional/trigger-workflow-and-wait@v1.6.1
#        with:
#          owner: stetind
#          repo: stem-documentation
#          github_token: ${{ secrets.COMPOSER_ACCESS_TOKEN }}
#          workflow_file_name: docs.yaml
#          wait_workflow: false
