name: CI

on:
  workflow_call:
    secrets:
      COMPOSER_ACCESS_TOKEN:
        required: true

env:
  PHP_VERSION: 8.1

#Cache libraries in between jobs
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - vendor/

before_script:
  # Install and run Composer
   name: 🧙 Install Dependencies
   uses: ramsey/composer-install@v2


jobs:
  duplication-check:
    name: Code duplication check
    runs-on: ubuntu-latest
    if: '! github.event.pull_request.draft'
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🔨 Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: phpcpd

      - name: 🔧 Check code duplication in "src" directory
        run: phpcpd src/ --min-lines=6

  pint:
    name: Laravel Pint Linting
    runs-on: ubuntu-latest
    needs: [ "arch-test" ]
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🔨 Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: 🧙 Configure Composer
        run: composer config --auth github-oauth.github.com "${{ secrets.COMPOSER_ACCESS_TOKEN }}"

      - name: 🔧  Run linter
        run: vendor/bin/pint -vv --config ruleset-pint.json --test

#  phpmd:
#    name: Php Mess Detector - Check
#    runs-on: ubuntu-latest
#    steps:
#      - name: 🛫 Checkout
#        uses: actions/checkout@v3
#
#      - name: 🔨 Setup php
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 8.1
#          tools: phpmd
#
#      - name: 🔧  Run Check
#        run: phpmd src text cleancode,codesize,controversial,design,unusedcode

  arch-test:
    name: Architecture Test
    runs-on: ubuntu-latest
    if: '! github.event.pull_request.draft'
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🔨 Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: 🧙 Configure Composer
        run: composer config --auth github-oauth.github.com "${{ secrets.COMPOSER_ACCESS_TOKEN }}"

      - name: 🚓 Run test
        run: vendor/bin/deptrac -v --report-uncovered --fail-on-uncovered


#  document:
#    name: Update Documentation
#    runs-on: ubuntu-latest
#    steps:
#      - name: 📖 Generate documentation
#        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} #I will only run on the main branch and not on pull request
#        uses: convictional/trigger-workflow-and-wait@v1.6.1
#        with:
#          owner: stetind
#          repo: stem-documentation
#          github_token: ${{ secrets.COMPOSER_ACCESS_TOKEN }}
#          workflow_file_name: docs.yaml
#          wait_workflow: false
