name: Delete Workflows

on:
  workflow_call:
    inputs:
      seconds:
        type: number
        default: 172800 # 2 days
        required: false

jobs:
  deleteWorkflow:
    runs-on: ubuntu-latest

    steps:
      - name: Deletion
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ github.repository }}
          older-than-seconds: ${{ inputs.seconds }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
