name: Release

on:
  workflow_call:

jobs:
  drafting-a-new-release:
    runs-on: ubuntu-latest
    name: 📖 Generate Release
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Code
        if: ${{ github.ref == 'refs/heads/main' }} #I will only run on the main branch and not on pull request
        uses: actions/checkout@v4

      - name: Check or create first tag #we need to initialize tags, in order to proceed to the next job
        run: |
          TAG="0.0.0"
          if [ $(git tag -l "${TAG}") ]; then
            gh release create 0.0.0
          fi
        env:
          GH_TOKEN: ${{ github.token }}


      - uses: sgpublic/delete-release-action@v1.1
        with:
          release-drop: false
          pre-release-drop: true
          pre-release-drop-tag: true
          pre-release-keep-count: -1
          draft-drop-count: -1
          draft-drop: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Calculate Next Semver Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          patchList: fix, bugfix, perf, ref, refactor, test, tests, chore, ci, docs, build
          noVersionBumpBehavior: current

      - name: Create Draft Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          prerelease: true
          draft: false
          commit: ${{ github.sha }}
          tag: ${{ steps.semver.outputs.nextStrict }}
          name: ${{ steps.semver.outputs.nextStrict }}
          body: '*pending...*'
          token: ${{ github.token }}

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.nextStrict }}
          writeToFile: false
          includeInvalidCommits: true

      - name: Create Release ${{ steps.semver.outputs.nextStrict }}
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          prerelease: true
          makeLatest: true
          tag: ${{ steps.semver.outputs.nextStrict }}
          name: ${{ steps.semver.outputs.nextStrict }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
