name: Release

on:
  workflow_call:

jobs:
  drafting-a-new-release:
    runs-on: ubuntu-latest
    name: 📖 Generate Release
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Code
        if: ${{ github.ref == 'refs/heads/main' }} #I will only run on the main branch and not on pull request
        uses: actions/checkout@v4

      - name: Check or create first tag #we need to initialize tags, in order to proceed to the next job
        run: |
          TAG="0.0.0"
          if [ $(git tag -l "${TAG}") ]; then
            gh release create 0.0.0
          fi
        env:
          GH_TOKEN: ${{ github.token }}


#      - name: Delete Old draft releases
#        run : |
#          gh release list --limit 10 |  while read -a line && [ ${line[1]} == Draft ] ; do
#             echo "deleting ${line[0]}" ;
#             gh release delete -y ${line[0]}  --cleanup-tag;
#          done;
#        env:
#          GH_TOKEN: ${{ github.token }}
      - name: Checkout latest release tag
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV



      - name: conventional changelog action
        id: changelog
        uses: TriPSs/conventional-changelog-action@latest
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          skip-version-file: true
          skip-commit: true
          skip-tag: true
          tag-prefix: ''
          fallback-version: $LATEST_TAG
          git-push: false
#
#
#      - name: Calculate Next Semver Version
#        id: semver
#        uses: ietf-tools/semver-action@v1
#        with:
#          token: ${{ github.token }}
#          patchList: fix, bugfix, perf, ref, refactor, test, tests, chore, ci, docs, build
#          noVersionBumpBehavior: current
#
      - name: Create Draft Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: true
          commit: ${{ github.sha }}
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.version }}
          body: ${{steps.changelog.outputs.clean_changelog}}
          token: ${{ github.token }}
#
#      - name: Update CHANGELOG  # he needs tags to work
#        id: changelog
#        uses: requarks/changelog-action@v1
#        with:
#          token: ${{ github.token }}
#          tag: ${{ steps.semver.outputs.nextStrict }}
#          writeToFile: false
#          includeInvalidCommits: true
#
#      - name: Create Release ${{ steps.semver.outputs.nextStrict }}
#        uses: ncipollo/release-action@v1.12.0
#        with:
#          allowUpdates: true
#          draft: true
#          prerelease: false
#          makeLatest: true
#          tag: ${{ steps.semver.outputs.nextStrict }}
#          name: ${{ steps.semver.outputs.nextStrict }}
#          body: ${{ steps.changelog.outputs.changes }}
#          token: ${{ github.token }}
