name: PR Labeler
on:
  workflow_call:

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label issue
        uses: TimonVS/pr-labeler-action@v4
        with:
          repo-token: ${{ github.token }}
          configuration-path: stetind/stem-reusable-workflows/.github/pr-labeler.yaml
