# https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

name: SONARCLOUD

on:
  workflow_call:
#    secrets: inherit
#      COMPOSER_ACCESS_TOKEN:
#        required: true
#      SONAR_TOKEN:
#        required: false

jobs:
  analyze:
    name: Sonar Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}