# https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

#
# Re-usable workflow for sonar checks
# Required secret variables:
# Per project:
# * SONAR_TOKEN : the sonar project token
#
#
# Usage:
#
#
# name: SONAR
#
# on:
#  push:
#    branches:
#      - master
#  pull_request:
#    types: [opened, synchronize, reopened]
# jobs:
#  analyze:
#    uses: stetind/stem-reusable-workflows/.github/workflows/sonar.yaml@main
#    secrets: inherit
#
name: SONARCLOUD

jobs:
  analyze:
    name: Sonar Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}