name: SONARCLOUD_MANUAL

on:
  workflow_call:
        
jobs:
  analyze:
    name: Sonar Check
    runs-on: ubuntu-latest
    steps:
      - if: "contains(github.event.head_commit.message, '>ci')"
        uses: stetind/stem-reusable-workflows/.github/workflows/sonar.yaml@main
        secrets: inherit
        
