name: SONARCLOUD_MANUAL

on:
  workflow_call:
        
jobs:
  analyze:
    name: Sonar Check
    runs-on: ubuntu-latest
    steps:
      - id: check_label
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          none_of: skip_sonar
          repo_token: ${{ secrets.GITHUB_TOKEN }}  
      - if: steps.check_label.outputs.label_check == 'success'
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - if: steps.check_label.outputs.label_check == 'success'
        name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
